# Generated by Django 5.2.6 on 2025-09-22 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Nubank, Itaú, etc.', max_length=100)),
                ('limite_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento', models.PositiveSmallIntegerField(help_text='Dia do vencimento da fatura (1-31)')),
                ('dia_fechamento', models.PositiveSmallIntegerField(help_text='Melhor dia para compra (1-31)')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cartão de Crédito',
                'verbose_name_plural': 'Cartões de Crédito',
                'ordering': ['nome'],
            },
        ),
    ]
