# Generated by Django 5.2.6 on 2025-09-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cofrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('objetivo', models.TextField(blank=True)),
                ('meta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoCofrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('deposito', 'Depósito'), ('resgate', 'Resgate')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cofrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='cofrinhos.cofrinho')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
    ]
