# Generated by Django 5.2.6 on 2025-09-22 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cofrinhos', '0001_initial'),
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentocofrinho',
            name='lancamento_geral',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimento_cofrinho', to='lancamentos.lancamento'),
        ),
    ]
