# Generated by Django 5.2.6 on 2025-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lancamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='pago',
            field=models.BooleanField(default=True, help_text='Indica se a transação afetou o caixa imediatamente'),
        ),
    ]
